window.SITE_SEARCH_INDEX = [
  { title: "首頁", url: "/", type: "頁面", keywords: "頤安本草 伍厚臻 中環 中醫" },
  { title: "關於伍厚臻醫師", url: "/about.html", type: "頁面", keywords: "醫師 資歷 25年 註冊 003769" },
  { title: "診症專科總覽", url: "/services.html", type: "專科", keywords: "服務 專科 痛症 皮膚 婦科" },
  { title: "痛症治療", url: "/services/pain.html", type: "專科", keywords: "頸痛 腰痛 坐骨神經 關節 肩周炎" },
  { title: "皮膚科", url: "/services/skin.html", type: "專科", keywords: "暗瘡 濕疹 敏感 脫髮" },
  { title: "內科調理", url: "/services/internal.html", type: "專科", keywords: "失眠 腸胃 疲勞 免疫" },
  { title: "婦科調理", url: "/services/gynaecology.html", type: "專科", keywords: "月經 痛經 不孕 PCOS 備孕" },
  { title: "針灸療法", url: "/services/acupuncture.html", type: "專科", keywords: "針灸 美顏針 減肥針" },
  { title: "中藥處方", url: "/services/herbs.html", type: "療法", keywords: "中藥 煎藥 沖劑 一人一方" },
  { title: "艾灸療法", url: "/services/moxibustion.html", type: "療法", keywords: "艾灸 溫通 祛寒" },
  { title: "拔罐療法", url: "/services/cupping.html", type: "療法", keywords: "拔罐 刮痧 活血" },
  { title: "中環暗瘡濕疹中醫", url: "/conditions/acne-eczema-central.html", type: "症狀", keywords: "中環 暗瘡 濕疹 中醫 養康 本草養康 肌膚養康 體質調理" },
  { title: "濕疹中醫治療", url: "/conditions/eczema.html", type: "症狀", keywords: "濕疹 皮膚炎 痕癢 異位性 養康" },
  { title: "暗瘡中醫治療", url: "/conditions/acne.html", type: "症狀", keywords: "暗瘡 痤瘡 荷爾蒙瘡 石頭瘡 養康" },
  { title: "失眠中醫調理", url: "/conditions/insomnia.html", type: "症狀", keywords: "失眠 睡眠 多夢 早醒" },
  { title: "不孕中醫調理", url: "/conditions/fertility.html", type: "症狀", keywords: "不孕 備孕 難孕 調經" },
  { title: "頸痛中醫治療", url: "/conditions/neck-pain.html", type: "症狀", keywords: "頸椎 落枕 肩頸僵硬" },
  { title: "坐骨神經痛", url: "/conditions/sciatica.html", type: "症狀", keywords: "坐骨 腰痛 下肢麻" },
  { title: "中環中醫診所", url: "/about/central-hk.html", type: "關於", keywords: "中環 皇后大道 錦安大廈 診所位置" },
  { title: "診所環境", url: "/clinic.html", type: "頁面", keywords: "診間 候診 環境 空間" },
  { title: "流程與收費", url: "/process.html", type: "頁面", keywords: "收費 診金 預約 付款" },
  { title: "常見問題", url: "/faq.html", type: "頁面", keywords: "FAQ 針灸 中藥 療程" },
  { title: "聯絡我們", url: "/contact.html", type: "頁面", keywords: "地址 電話 WhatsApp 預約" },
  { title: "養生專欄", url: "/blog/", type: "專欄", keywords: "中醫冷知識 文章 養生" },
  { title: "濕疹為何要從內調？", url: "/blog/eczema-from-within.html", type: "專欄", keywords: "濕疹 脾濕 內外同治" },
  { title: "暗瘡位置與臟腑", url: "/blog/acne-face-zones.html", type: "專欄", keywords: "暗瘡 額頭 下巴 內分泌" },
  { title: "失眠的中醫分型", url: "/blog/insomnia-tcm-guide.html", type: "專欄", keywords: "失眠 心腎不交 肝鬱" },
  { title: "壓力型難孕體質", url: "/blog/fertility-stress.html", type: "專欄", keywords: "不孕 壓力 衝任 針灸" },
  { title: "最新消息", url: "/news/", type: "消息", keywords: "診所 公告 營業" },
  { title: "週六應診時間更新", url: "/news/saturday-hours-2026.html", type: "消息", keywords: "應診 時間 週六" }
];
