/**
 * Browser-less layout metrics from built HTML structure hints.
 * For true overflow, use browser CDP or Puppeteer.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

const ISSUES = [
  {
    id: 'L01',
    severity: 'critical',
    area: '首頁 · 應診時間表',
    pages: 'index.html, en/index.html',
    viewports: '320–639px',
    locales: '中 + 英',
    problem: '`.df-home-hours__head/row` 固定 `grid-template-columns: 1.4fr 1fr 1fr`，無任何 @media。窄螢幕三欄擠壓，EN 星期名更長時欄位重疊或文字溢出。',
    file: 'css/home.css:682–692',
  },
  {
    id: 'L02',
    severity: 'high',
    area: '導航 · 標頭',
    pages: '全站',
    viewports: '640–1279px',
    locales: '中 + 英（EN 更嚴重）',
    problem: '`.df-nav__cta` 640px 即顯示，但漢堡 1280px 才隱藏。平板橫向同一列容納 logo + 漢堡 + EN + 搜尋 + CTA，品牌 `white-space:nowrap` 無退路。',
    file: 'css/dongfang.css:100–103, 276–281',
  },
  {
    id: 'L03',
    severity: 'high',
    area: '導航 · 桌面',
    pages: '全站',
    viewports: '1280–1400px',
    locales: '中 + 英',
    problem: '`.df-nav__inner` 1280px 改 `flex-wrap:nowrap`，6 個 dropdown + 連結 + 右側工具列，`flex-shrink:0` + nowrap 可能溢出或被裁切。',
    file: 'css/dongfang.css:91–95, 171–173',
  },
  {
    id: 'L04',
    severity: 'high',
    area: '首頁 · 預約 funnel',
    pages: 'index.html, en/index.html',
    viewports: '320–479px',
    locales: '中 + 英',
    problem: '`.df-funnel__options` 永遠 `grid-template-columns: 1fr 1fr`。EN「Gynaecology」「Internal medicine」在 320px 雙欄按鈕文字換行過多、高度不一，視覺不齊。',
    file: 'css/home.css:866–877',
  },
  {
    id: 'L05',
    severity: 'medium',
    area: '首頁 · Hero',
    pages: 'en/index.html',
    viewports: '320–767px',
    locales: '英',
    problem: 'EN 品牌水印 `html[lang="en"] .df-home-hero__type-en-brand--in-main` 絕對定位疊在 h1 區，小螢幕可能與標題/CTA 視覺重疊。ZH 用中央 grid 水印，兩語 hero 構圖不對稱。',
    file: 'css/home.css:128–146, 252–261',
  },
  {
    id: 'L06',
    severity: 'medium',
    area: '內頁 · Hero 水印',
    pages: 'about, services, faq, blog, conditions 等',
    viewports: '320–480px',
    locales: '中 + 英',
    problem: '`.df-page-hero__watermark` 中文 `font-size:24vw`；EN `white-space:nowrap; max-width:min(48vw,460px)`。長 EN 水印（如 Traditional、Gynaecology）在極窄螢幕可能被裁切。',
    file: 'css/dongfang.css:310–321',
  },
  {
    id: 'L07',
    severity: 'medium',
    area: '首頁 · 價目表',
    pages: 'index.html, en/index.html',
    viewports: '320–480px',
    locales: '中 + 英',
    problem: '`.df-home-price-list li` flex 左右排列，`.df-home-price-list__amt { white-space:nowrap }`。長服務名（EN 更長）與價格競爭水平空間，可能擠壓或換行不一致。',
    file: 'css/home.css:716–728',
  },
  {
    id: 'L08',
    severity: 'medium',
    area: '首頁 · 照片卡',
    pages: 'index.html, en/index.html',
    viewports: '全寬',
    locales: '中 + 英',
    problem: '`.df-photo-card__deco { left/right: -16px }`、`.df-photo-card__logo { top:-40px }` 超出卡片邊界；父層無 overflow:hidden，在部分瀏覽器可能觸發水平捲動（雖 html/body 有 overflow-x clip/hidden 掩蓋）。',
    file: 'css/home.css:366–385',
  },
  {
    id: 'L09',
    severity: 'medium',
    area: 'Sticky CTA + WA 浮動鈕',
    pages: 'index.html, en/index.html',
    viewports: '≤1023px',
    locales: '中 + 英',
    problem: '底部 sticky bar (z:45) + WA float (z:50) 共存。滾動至 booking 區前，雙轉化元素堆疊右下角；footer 僅 ≤767px 有額外 padding-bottom，768–1023 平板 footer 與 sticky 間距略緊。',
    file: 'css/home.css:919–949; css/dongfang.css:543',
  },
  {
    id: 'L10',
    severity: 'medium',
    area: 'Footer',
    pages: '全站',
    viewports: '768px 臨界點',
    locales: '中 + 英',
    problem: '`.df-footer__grid` 768px 直接跳四欄，無 768–1024 二欄過渡。sitemap 768→2欄、1024→4欄，臨界點版面跳動（CLS 風險）。',
    file: 'css/dongfang.css:519–520, 805–810',
  },
  {
    id: 'L11',
    severity: 'low',
    area: '表單',
    pages: 'contact, index booking',
    viewports: '640–767px',
    locales: '中 + 英',
    problem: '`.df-form-row` / `.df-home-form__grid` 640–768px 即兩欄，欄位偏窄；EN label 較長時 input 區高度不一致。',
    file: 'css/dongfang.css:497; css/home.css:797',
  },
  {
    id: 'L12',
    severity: 'low',
    area: '中/英 typography',
    pages: '全站',
    viewports: '全寬',
    locales: '英 vs 中',
    problem: '`.lang-en` 與 `html[lang="en"]` 混用；EN 改 Cormorant/Noto Serif、字距縮小，同區塊高度/換行點與中文不同，section 垂直節奏略有不齊（設計取捨，非 bug）。',
    file: 'css/dongfang.css:132–139; css/home.css:932–935',
  },
  {
    id: 'L13',
    severity: 'low',
    area: '全局 overflow 掩蓋',
    pages: '全站',
    viewports: '全寬',
    locales: '中 + 英',
    problem: '`html { overflow-x:clip }` + `body { overflow-x:hidden }` 裁切溢出但不修正根因，部分元素仍可能 visually bleed 或被裁切。',
    file: 'css/dongfang.css:18, 23',
  },
  {
    id: 'L14',
    severity: 'info',
    area: 'NAV 功能（已修復待部署）',
    pages: '全站',
    viewports: '<1280px',
    locales: '中 + 英',
    problem: 'paper-grain 堆疊導致 drawer 點擊失效 — 本地已修，Vercel 線上版可能仍存在。',
    file: 'css/dongfang.css:43–47',
  },
];

console.log(JSON.stringify({ total: ISSUES.length, bySeverity: {
  critical: ISSUES.filter(i => i.severity === 'critical').length,
  high: ISSUES.filter(i => i.severity === 'high').length,
  medium: ISSUES.filter(i => i.severity === 'medium').length,
  low: ISSUES.filter(i => i.severity === 'low').length,
  info: ISSUES.filter(i => i.severity === 'info').length,
}, issues: ISSUES }, null, 2));
